### ISSUE TITLE
pyproject.toml:  Misspelled key of liccheck tool

### ISSUE THREAD

**Issue by jenisys** [thehale/git-authorship#81]
`liccheck` key is misspelled in `pyproject.toml` file

```toml
# — FILE: pyproject.toml
[tool.liccheck]
authorized_licenses = [  # OK, correctly spelled.
   # …
]

unautorized_licenses = [  # HERE_IS_THE_PROBLEM_POINT
]
# —- SHOULD BE:
unauthorized_licenses = [
]
```

SEE:
* [pyproject.toml](https://github.com/thehale/git-authorship/blob/master/pyproject.toml)
* https://github.com/dhatim/python-license-check#how-to-use
